################################################################################
#
# template_xml_config_transform
# This template will transform XML config files (i.e. App.config)
# Requires a corresponding release config file (i.e. App.Release.config),
# that has XML transformation syntax
# https://learn.microsoft.com/en-us/previous-versions/aspnet/dd465326(v=vs.110)
#
# REVISION HISTORY
# KG - 1/19/2024 - Initial Version
#
################################################################################

parameters:
- name: archiveFilePath
  default: ''
- name: baseConfigFileName
  default: '**/App.config'
- name: releaseConfigFileName
  default: '**/App.Release.config'

steps:
- task: FileTransform@2
  displayName: 'File transformation: ${{ parameters.baseConfigFileName }}'
  inputs:
    folderPath: '${{ parameters.archiveFilePath }}'
    xmlTransformationRules: '-transform ${{ parameters.releaseConfigFileName }} -xml ${{ parameters.baseConfigFileName }}'
    xmlTargetFiles: '${{ parameters.baseConfigFileName }}'
